stages:
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y unzip

variables:
  TF_VERSION: "1.6.5"  
test:
  stage: test
  script:
    - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
    - terraform --version
    - terraform init -backend=false
    - terraform validate
    - terraform fmt -check=true
    - terraform plan -out=tfplan
    - terraform show -json tfplan > tfplan.json
    - rm -f terraform_${TF_VERSION}_linux_amd64.zip
